module.exports = {
  apps: [
    {
      name: "acs-api",
      script: "apps/api/dist/index.js",
      cwd: __dirname + "/../..",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        APP_ENV: "production",
        APP_VERSION: "1.0.0-rc",
        API_PORT: 3001,
        USE_MEMORY_QUEUE: "false",
        USE_REDIS_QUEUE: "true",
      },
      error_file: "logs/pm2-api-error.log",
      out_file: "logs/pm2-api-out.log",
      merge_logs: true,
      max_memory_restart: "512M",
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
    {
      name: "acs-worker",
      script: "apps/worker/dist/index.js",
      cwd: __dirname + "/../..",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        APP_ENV: "production",
        APP_VERSION: "1.0.0-rc",
        USE_MEMORY_QUEUE: "false",
        USE_REDIS_QUEUE: "true",
        WORKER_CONCURRENCY: 2,
      },
      error_file: "logs/pm2-worker-error.log",
      out_file: "logs/pm2-worker-out.log",
      merge_logs: true,
      max_memory_restart: "768M",
      kill_timeout: 10000,
    },
    {
      name: "acs-admin",
      script: "apps/admin/server.js",
      cwd: __dirname + "/../../apps/admin/.next/standalone/apps/admin",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3002,
        NEXT_PUBLIC_API_BASE: "http://localhost:3001",
      },
      error_file: "logs/pm2-admin-error.log",
      out_file: "logs/pm2-admin-out.log",
      merge_logs: true,
      max_memory_restart: "384M",
    },
  ],
};
